version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: test_1-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
       MYSQL_USER: user
       MYSQL_PASSWORD: password
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: testdb
    ports:
      - "6606:3306"